### ISSUE TITLE
Count PRs vs. Commits

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/FsharpLearning#6]
for the GitHub statistics that we are tracking, do we count merged PRs or Commits

What is the 'correct' level of scorekeeping that we should track?

**Comment by bravecobra** [comment]
Shouldn't this be discussed at https://github.com/csharpfritz/Fritz.StreamTools/issues/127?

**Comment by csharpfritz** [comment]
Sure... let's move it over there...
